### ISSUE TITLE
Document use with workspaces

### ISSUE THREAD

**Issue by virtualritz** [phil-opp/cargo-post#9] opened 2020-06-22 20:15 UTC
When I run `cargo post build` in a workspace where each member has their own `post_build.rs` I get this: 
```
thread 'main' panicked at 'Please specify a `--package` argument', src/main.rs:109:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: cargo_post::run_post_build_script
   8: cargo_post::main
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal
  11: std::rt::lang_start
  12: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I have no idea what it means or where to specify this `--package` parameter (and what value it should take). :)
Could you clarify and maybe add some note to the REAMDE/docs?

**Comment by phil-opp** [comment] 2020-06-23 07:31
The problem is that a workspace contains multiple packages, but we currently only support post build scripts for a single package. So you have to pass a `--package` parameter to `cargo` to specify which workspace member you like to build.

I think it should be possible to also support building multiple members at once, but I don't have the time to implement the required changes for this currently.

**Comment by virtualritz** [comment] 2020-06-23 09:55
Ok, maybe add a hint that `--package` is a `cargo` parameter and not a `cargo-post` one.
I tried `cargo post --package foo build` w/o much success.

I'm now need something to call `cargo post build` for each of my packages. At this point I need to use yet another build tool so I am switching the whole post-build stuff to CMake.

**Comment by meyerphi** [comment] 2020-06-29 15:19
Another issue is that the temporary package `post-build-script` is not part of the workspace, and then cargo complains. Take a `Cargo.toml` with content
```
[package]
name = "foo"
version = "0.1.0"

[workspace]
members = [ "bar"]
```
together with a library crate in the subfolder `bar` and a `post_build.rs` script. Executing `cargo post build --package foo` results in the following error:
```
Running Post Build Script at /tmp/foo/post_build.rs
error: current package believes it's in a workspace when it's not:
current:   /tmp/foo/target/post_build_script_manifest/Cargo.toml
workspace: /tmp/foo/Cargo.toml

this may be fixable by adding `target/post_build_script_manifest` to the `workspace.members` array of the manifest located at: /tmp/foo/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
```
This can be fixed by adding `exclude = ["target"]` to the `[workspace]` section, but that should also be documented.

**Comment by johalun** [comment] 2020-07-05 13:51
+1 for workspace support. If I add the exclude = ["target'] to the crate then all post-build deps will be built _again_ in the crate's target dir, instead of utilizing what already cached in the workspace's target dir.

**Closed** 2020-07-19 15:41 UTC

**Comment by johalun** [comment] 2020-07-20 16:47
Thanks for fixing this! Now I can remove that pesky Makefile and stay pure Rust :+1:
