### ISSUE TITLE
Wrong post-build if .cargo/config contains build target

### ISSUE THREAD

**Issue by MathiasKoch** [phil-opp/cargo-post#16] opened 2021-01-13 07:59 UTC
If `.config/cargo` contains a build target where `std` is not available, post-build will fail, as it tries to compile post-build for said target. 

`.cargo/config`:
```toml
[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)
```

`post_build.rs`:
```rust
use std::{path::PathBuf, env};

fn main() {
    let current_dir = env::current_dir().unwrap();
    let current_parent = current_dir.parent().unwrap();
    println!("current_dir: {:?}", current_dir);
    println!("current_parent: {:?}", current_parent);
    println!("ok");
}
```

`cargo post build -p factbird-rs`:
```
Finished dev [optimized + debuginfo] target(s) in 0.03s
Running Post Build Script at /home/mathias/git/blackbird/factbird-mini/factbird-rs/post_build.rs
   Compiling post-build-script v0.1.0 (/home/mathias/git/blackbird/factbird-mini/target/post_build_script_manifest)
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `post-build-script`

To learn more, run the command again with --verbose.
```

I can't quite figure out if this is actually the same as #2 ?

As i see it, the post_build script should always be run using the host target, and never be influenced by `.config/cargo` target?

**Comment by phil-opp** [comment] 2021-01-13 09:11
Thanks for reporting! The issue is that `.cargo/config` files apply to all cargo invocations in that directory. Unfortunately, there is currently no way (e.g. a command line flag) to unset a default target for a single invocation.

I also encountered this underlying problem many times, e.g. as described here: https://github.com/rust-lang/cargo/pull/8757#issuecomment-713897532. I now think the best solution for this is https://internals.rust-lang.org/t/proposal-move-some-cargo-config-settings-to-cargo-toml/13336, which would allow to specify the default target as a package-specific key in the `Cargo.toml`. There is already an implementation for this in https://github.com/rust-lang/cargo/pull/9030, let's hope it gets merged soon.

**Comment by MathiasKoch** [comment] 2021-01-13 12:54
Hmm, okay. 
So what i hear you say, is that there is not even a work-around currently? 

Lets hope for https://github.com/rust-lang/cargo/pull/9030 soon :)

**Comment by phil-opp** [comment] 2021-01-14 13:59
The only workaround that I'm aware of is to not use a default target and instead pass it as `--target` argument on the command line. Alternatively, you can create a [custom alias](https://doc.rust-lang.org/cargo/reference/config.html#alias) for this for easier typing (e.g. `cargo arm-build` or `cargo xbuild`).

**Comment by MathiasKoch** [comment] 2021-01-15 08:00
It seems to work if i remove the default target, and builds with `cargo post build --target ... --release`, but the custom alias to make this easier, does not seem to work as expected, due to https://github.com/phil-opp/cargo-post/blob/ef1b4d097ead5e338870251fa4d464ca87cb4b4c/src/main.rs#L42-L53

An alias like
```toml
[alias]
br = "build --release --target thumbv7em-none-eabihf"
```
Will always result in `unknown cargo command 'cargo br'`

**Comment by phil-opp** [comment] 2021-01-15 11:24
Have you tried including the `post` in the alias, i.e. `br = "post build --release --target thumbv7em-none-eabihf"`?

**Comment by MathiasKoch** [comment] 2021-01-15 13:16
Ahh, no haven't tried that. Will give it a shot

**Closed** 2021-12-22 10:20 UTC
